package events

type ServerEvent string

const (
	ServerCreateEvent             ServerEvent = "ServerCreateEvent"
	ServerStoppedEvent            ServerEvent = "ServerStoppedEvent"
	ServerShutdownEvent           ServerEvent = "ServerShutdownEvent"
	ServerActionEvent             ServerEvent = "ServerActionEvent"
	ServerRestartEvent            ServerEvent = "ServerRestartEvent"
	ServerKilledEvent             ServerEvent = "ServerKilledEvent"
	ServerCommandDispatchEvent    ServerEvent = "ServerCommandDispatchEvent"
	ServerCommandEvent            ServerEvent = "ServerCommandEvent"
	ServerCommandPreprocessEvent  ServerEvent = "ServerCommandPreprocessEvent"
	ServerFileUploadEvent         ServerEvent = "ServerFileUploadEvent"
	ServerFileDownloadEvent       ServerEvent = "ServerFileDownloadEvent"
	ServerFileDeleteEvent         ServerEvent = "ServerFileDeleteEvent"
	ServerFileMoveEvent           ServerEvent = "ServerFileMoveEvent"
	ServerFileCopyEvent           ServerEvent = "ServerFileCopyEvent"
	ServerFileCompressEvent       ServerEvent = "ServerFileCompressEvent"
	ServerFileDecompressEvent     ServerEvent = "ServerFileDecompressEvent"
	ServerFileListEvent           ServerEvent = "ServerFileListEvent"
	ServerFileFindEvent           ServerEvent = "ServerFileFindEvent"
	ServerCreateBackupEvent       ServerEvent = "ServerCreateBackupEvent"
	ServerRestoreBackupEvent      ServerEvent = "ServerRestoreBackupEvent"
	ServerDeleteBackupEvent       ServerEvent = "ServerDeleteBackupEvent"
	ServerListBackupsEvent        ServerEvent = "ServerListBackupsEvent"
	ServerStartBackupEvent        ServerEvent = "ServerStartBackupEvent"
	ServerBackupCompleteEvent     ServerEvent = "ServerBackupCompleteEvent"
	ServerBackupFailedEvent       ServerEvent = "ServerBackupFailedEvent"
	ServerBackupProgressEvent     ServerEvent = "ServerBackupProgressEvent"
	ServerSubuserCreateEvent      ServerEvent = "ServerSubuserCreateEvent"
	ServerSubuserDeleteEvent      ServerEvent = "ServerSubuserDeleteEvent"
	ServerSubuserUpdateEvent      ServerEvent = "ServerSubuserUpdateEvent"
	ServerSubuserListEvent        ServerEvent = "ServerSubuserListEvent"
	ServerSuspensionEvent         ServerEvent = "ServerSuspensionEvent"
	ServerUnSuspensionEvent       ServerEvent = "ServerUnSuspensionEvent"
	ServerTransferEvent           ServerEvent = "ServerTransferEvent"
	ServerInstallEvent            ServerEvent = "ServerInstallEvent"
	ServerUpdateEvent             ServerEvent = "ServerUpdateEvent"
	ServerInstallFailedEvent      ServerEvent = "ServerInstallFailedEvent"
	ServerUpdateFailedEvent       ServerEvent = "ServerUpdateFailedEvent"
	ServerInstallStartedEvent     ServerEvent = "ServerInstallStartedEvent"
	ServerUpdateStartedEvent      ServerEvent = "ServerUpdateStartedEvent"
	ServerInstallCompletedEvent   ServerEvent = "ServerInstallCompletedEvent"
	ServerUpdateCompletedEvent    ServerEvent = "ServerUpdateCompletedEvent"
	ServerDeleteEvent             ServerEvent = "ServerDeleteEvent"
	ServerDeleteFailedEvent       ServerEvent = "ServerDeleteFailedEvent"
	ServerDeleteStartedEvent      ServerEvent = "ServerDeleteStartedEvent"
	ServerDeleteCompletedEvent    ServerEvent = "ServerDeleteCompletedEvent"
	ServerGracePeriodStartedEvent ServerEvent = "ServerGracePeriodStartedEvent"
	ServerGracePeriodEndedEvent   ServerEvent = "ServerGracePeriodEndedEvent"
	ServerExpiredEvent            ServerEvent = "ServerExpiredEvent"
	ServerRenewEvent              ServerEvent = "ServerRenewEvent"
	ServerRenewFailedEvent        ServerEvent = "ServerRenewFailedEvent"
)
